### ISSUE TITLE
Horizontal scroll bars location

### ISSUE THREAD

**Issue by asteng88** [asteng88/PyPredict#2]
The location of the horizontal scroll bars is stuck on the right-hand side underneath the vertical scroll bars. 
Need to be moved underneath the excel data display.
![Horizontal Scrool Bars](https://github.com/user-attachments/assets/efd9810b-8780-4f3d-9cf4-a7bf58b449dc)

**Comment by pr4j3sh** [comment]
Hey @asteng88 I was able to fix this issue.

## screenshot
![ss-20241001-181328Z-current](https://github.com/user-attachments/assets/41f66dab-dd66-49f4-8ad5-6c20517e0006)

## issue
the issue occurs because you packed the horizontal scrollbar after packing the canvas and vertical scrollbar. In Tkinter, packing elements in a frame affects their layout, and by default, each widget is packed from top to bottom or left to right unless explicitly specified.

## solution
so I used `grid` layout and that fixed the scrollbars

> You may assign me this issue and I'll create a PR accordingly

**Comment by asteng88** [comment]
Great @prajeshElEvEn!
Assigned to you!

**Comment by pr4j3sh** [comment]
> Great @prajeshElEvEn! Assigned to you!

created a [pull request](https://github.com/asteng88/PyPredict/pull/5)
